#!/bin/sh

if [ "$#" -lt 3 ]
then
	echo "Usage: $0 <docker_app_name> <tarfile_url> <out folder> <opt args...>"
	exit 1
fi

DOCKER_NAME=$1
TESTDATA_URL=$2
OUT_FOLDER=$3

shift 3

OPTARGS=$@

TARFILE=${TESTDATA_URL##*/}

mkdir -p bids 
wget -qO- $TESTDATA_URL > $TARFILE 
docker create -v /data --name testdata alpine:3.4 /bin/true
docker cp $TARFILE testdata:/data
docker run  --name testapp  --volumes-from testdata -it $DOCKER_NAME $OPTARGS -o /out /data/$TARFILE
retval=$?
docker cp testapp:/out $OUT_FOLDER

echo "return value: $retval"
exit $retval
