#!/bin/bash

if [ "$#" -lt 1 ]
then
    echo "Usage: $0 <in_bids> <subj ID> <session id (optional)>"
	exit 1
fi 
in_bids=$1


#assumes python script is in same folder as this wrapper -- eventually just replace this..
exec_path=`dirname $0`

subj=$2
subj=${subj##sub-} #strip off sub- if it exists, to make consistent

if [ "$#" -gt 2 ]
then
    ses=$3
	ses=${ses##ses-} #strip off sub- if it exists, to make consistent
fi
 


	if [ -n "$ses" ]
    then
        out_folder=sub-$subj/ses-$ses
    else
        out_folder=sub-$subj
    fi

	$exec_path/meGRE_bids_corrector.py $in_bids/$out_folder/anat

	#fix ImagingFrequency by getting from another json file
	match=`grep ImagingFrequency $in_bids/$out_folder/anat/*.json | head -n 1`
	freq=${match##*:\ }
	freq=${freq%%,*}

	$exec_path/fixImFreq_json.py $in_bids/$out_folder/anat $freq


	$exec_path/memp2rage_bids_corrector.py $in_bids/$out_folder/anat

	$exec_path/pdt2_bids_corrector.py $in_bids/$out_folder/anat

	$exec_path/magphase_sa2rage_bids_corrector.py $in_bids/$out_folder/fmap
