#!/bin/bash

if [ "$#" -lt 1 ]
then
	echo "Usage: $0 <in_bids> <optional list of subj IDs>"
	exit 1
fi 
in_bids=$1

exec_path=`dirname $0`


if [ "$#" -gt 1 ]
then
	subjlist=`cat $2`
		#list of (new) subject IDs to process, where ID is from sub-ID
else
	subjlist=`tail -n +2 $in_bids/participants.tsv | awk '{print $1}' `
fi
#correct field map json files


for subj in $subjlist
do

	subj=${subj##sub-} #strip off sub- if it exists, to make consistent
	$exec_path/correctFieldMapJson.py $in_bids sub-$subj


done
