#!/bin/bash

if [ "$#" -lt 3 ]
then
	echo "Usage: <expression that includes {subject} (and optionally {session})> <tagname to search for (i.e. subject or session)> <input string/filename>"
	exit 1
fi



subj_expr=$1
searchtag=$2
in_name=$3

result=

	before=${subj_expr%%\{*}
	between=${subj_expr#*\}}
	between=${between%%\{*}
	after=${subj_expr##*\}}

#	echo subj_expr: $subj_expr
#	echo before: $before
#	echo between: $between
#	echo after: $after

	if [ "$between" = "$after" ]
	then
		#only one tagname, get it
		
		#grep subject or session
		if echo $subj_expr | grep -q "{$searchtag}"
		then
			#now want to replace before string from in_name
			stripfront=`echo $in_name | sed -e "s/$before//"`

			if [ -n "$after" ]
			then
			result=`echo $stripfront | sed -e "s/$after//"`
			else
			result=$stripfront
			fi

	
		else
			echo "$searchtag not found in $subj_expr" >&2
			exit 1

		fi
#		echo result $result

	else
		#echo "multiple tags", want to replace the before and after 
		
		#want to replace before{ with blank
#		echo $subj_expr 
#	       echo	sed -e "s/${before}{//"
#	       echo "$subj_expr" | sed -e "s/${before}{//"
		tag1=${subj_expr#$before\{}
		tag1=${tag1%%\}*}

		tag2=${subj_expr#$before\{$tag1\}$between\{}
		tag2=${tag2%%\}*}
#		echo tag1: $tag1
#		echo tag2: $tag2

		if [ "$tag1" = "$searchtag" ]
		then
#			echo in_name $in_name
			result=${in_name##$before}
#			echo result $result after stripping $before longest from beginning
			result=${result%%$between*}
#			echo result $result after stripping $between* longest from end

		elif [ "$tag2" = "$searchtag" ]
		then
#			echo in_name $in_name
			result=${in_name##*$between}
#			echo result $result after stripping *$between longest from beginning
			result=${result%$after}
#			echo result $result after stripping $after shortest from end
		else
			echo "$searchtag not found in $subj_expr" >&2
			exit 1
		fi

			
	fi

	if [ -n "$result" ]
	then
		echo $result
	fi

exit 0


