#!/bin/bash

if [ "$#" -lt 3 ]
then
	echo "Usage: <expression that includes {subject} (and optionally {session})> <tagname to search for (i.e. subject or session)> <input string/filename>"
	exit 1
fi



subj_expr=$1
searchtag=$2
in_name=$3

result=

	before=${subj_expr%%\{*}
	between=${subj_expr#*\}}
	between=${between%%\{*}
	after=${subj_expr##*\}}

#	echo subj_expr: $subj_expr
#	echo before: $before
#	echo between: $between
#	echo after: $after

	if [ "$between" = "$after" ]
	then
		#only one tagname, get it  -- 
		
		#grep subject or session
		if echo $subj_expr | grep -q "{$searchtag}"
		then
			#now want to replace before string from in_name
			stripfront=${in_name##$before}
#			echo stripfront $stripfront
			if [ -n "$after" ]
			then
			result=`echo $stripfront | sed -e "s/$after//"`
#			echo result $result
			else
			result=$stripfront
			fi

	
		else
			echo "$searchtag not found in $subj_expr" >&2
			exit 1

		fi

	else

		#find out whether tag1 is subject or session
		nc_subj=`echo $subj_expr | grep -bo "{subject}" | cut -d: -f1`
		nc_sess=`echo $subj_expr | grep -bo "{session}" | cut -d: -f1`

#		echo nc_subj $nc_subj nc_sess $nc_sess
		if [ $nc_subj -lt $nc_sess ]
		then
			tag1n=subject
			tag2n=session
		else
			tag1n=session
			tag2n=subject
		fi

		
		#if there is a * in before, then find tag2 first and strip it off before finding tag1 
		#if there is a * in after, then find tag 1 first, and strip it off before finding tag2

		#case1

		#get tag2 result
		result=${in_name%%$after}
#		echo result $result
		tag2result=${result##${before}*${between}}
#		echo tag2result $tag2result
		
		#now use this to get tag1 result 
		result=${in_name%%${between}${tag2result}}
		tag1result=${result##${before}}
#		echo tag1result $tag1result
		

		if [ "$tag1n" = "$searchtag" ]
		then
			result=$tag1result
		elif [ "$tag2n" = "$searchtag" ]
		then
			result=$tag2result
		else
			echo "$searchtag not found in $subj_expr" >&2
			exit 1
		fi

			
	fi

	if [ -n "$result" ]
	then
		echo $result
	fi

exit 0


